[general]
scheme = 1
route = "307"

[stop]
distAvg = 350
distSd = 70

[signal]
distAvg = 250
distSd = 30

[schedule]
startTime = "0000"
endTime = "0100"
intervalAvg = 5
sd = 1

[velocity]
avg = 25
sd = 7
limit = 40
low = 15


