[general]
scheme = 1
route = "307"
morningPeak = "0700-0900"
eveningPeak = "1700-1900"

[stop]
distAvg = 350
distSd = 70

[signal]
distAvg = 250
distSd = 30

[schedule]
startTime = "0000"
endTime = "0100"
avg = 5
sd = 1
shift = 12

[velocity]
avg = 25
sd = 7
limit = 40
low = 15


